### ISSUE TITLE
z "A" goes to subdir "A/B"

### ISSUE THREAD

**Issue by aj3423** [jethrokuan/z#105]
There is directory 

```
~ > z server
/e/wa/server >
```
This is ok, but 
```
~ > z wa
/e/wa/server >
```
Why the second also goes to dir "server"? Is `z wa` supposed to be dir "/e/wa" ?

**Comment by krobelus** [comment]
I think that's intentional, because you might have several directories with the same basename, like

```
project1/src
project2/src
```

if you change to `/e/wa` more often than `/e/wa/server`, then the former will also be prioritized, so that's an easy workaround
