### ISSUE TITLE
Doesn't work with paths with hyphens in them

### ISSUE THREAD

**Issue by tom-james-watson** [jethrokuan/z#106]
I have some folders like `my-folder`. If I ever run any `z` command with a `-` in it, e.g. `z my-folder`, then it consistently fails to find any results and doesn't change directory.

Have confirmed on macOS 11.6.2 and Ubuntu 21.10.

Thanks for the awesome script by the way - much appreciated!

**Comment by krobelus** [comment]
works for me, can you check `fish_trace=1 z my-folder`

**Comment by krobelus** [comment]
_zlua is coming from somewhere else, try to get rid of that.

If this works in `HOME=(mktemp -d) fish` (that is install inside the temporary HOME), then _zlua is lurking somewhere in your $HOME

**Comment by tom-james-watson** [comment]
Yeah sorry it looks like I had a different version of fish-based z. Not actually sure where it came from. I've pulled in your version from fresh and can confirm it works as expected. Thanks!
