### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by nunojesus** [jethrokuan/z#64]
Hi Hello I am looking for open source projects to contribute graphical design, I have done several jobs for free in opensource projects, I would like to know if you are interested that I make a logo for this your project ?.

Greetings

Nuno Jesus

**Comment by jethrokuan** [comment]
Hi Nuno, that's a very generous offer! I'd gladly accept a logo PR. However, do note that this is a port of the [original z project](http://github.com/rupa/z), so you should either: (1) contribute/offer to contribute a logo to that repo if it's not fish-specific, or (2) design a logo that makes sense for this port. Thanks!
