### ISSUE TITLE
prints a blank line in Fish version 3.0.2

### ISSUE THREAD

**Issue by Benjamin-Lee** [jethrokuan/z#74]
I just updated to Fish 3.0.2 and am now having `z` print a blank line after changing directories:

```
/ ❯❯❯ z desktop

~/Desktop ❯❯❯
```

When it used to do
```
/ ❯❯❯ z desktop
~/Desktop ❯❯❯
```

This does not happen when I just type `z`:
```
~/D/P/Research ❯❯❯ z
~/D/P/Research ❯❯❯
```
Any ideas?

**Comment by krobelus** [comment]
My bad, this should be fixed now
