### ISSUE TITLE
string escape: Invalid escape style 'regex'

### ISSUE THREAD

**Issue by agarzon** [jethrokuan/z#75]
Since recent updates, now I get this message with uses z command.

```
string escape: Invalid escape style 'regex'
``` 

Still lands in the correct folder as before, but always showing that warning.

And this is very well related with the latest commit: https://github.com/jethrokuan/z/commit/4909feac4538592733c677060d9106e9beadbb19

**Comment by krobelus** [comment]
Should be fixed now, I tested it on fish 2.7 and 3.0

**Comment by agarzon** [comment]
Updated the plugin, the problem persist.

**Comment by jethrokuan** [comment]
@agarzon can you post your fish version information?

**Comment by agarzon** [comment]
All the most recent:

➜ fish --version
fish, version 2.7.1

➜ fisher --version
fisher version 3.2.8 ~/.config/fish/functions/fisher.fish

➜ cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

**Comment by krobelus** [comment]
@agarzon Sorry for the troubles, I accidentally pushed to the wrong remote. Now that https://github.com/jethrokuan/z/commit/c398f1dd944ceba0cee9d1710c370d27763fb867 is in, this should finally be fixed.

**Comment by jethrokuan** [comment]
@krobelus looks like in fish to redirect both stdout and stderr somewhere the redirection comes last:

`string escape --style=rege > /dev/null 2>&1`

**Comment by agarzon** [comment]
Tested, all good now. 👍
