### ISSUE TITLE
How can regular expressions be used as parameters?

### ISSUE THREAD

**Issue by fresswolf** [jethrokuan/z#79]
In the examples and test cases I don't see any regular expressions used. Can they be used? How would I jump to a path ending with foo? (not matching /path/foobar but matching /path/foo and /path/foofoo)

**Comment by jethrokuan** [comment]
`z` can't be used that way, if you want to jump to a specific folder matching a string, consider using tab complete `z foo <TAB>` should contain the folder you want in the completion list.

**Comment by fresswolf** [comment]
Ok thanks for the clarification, I think I can live with that. I just wondered if it was possible because the documentation names the command's arguments "regex1" and "regex2". This is misleading and should be renamed in my opinion

**Comment by jethrokuan** [comment]
Right, yes my bad, thanks for the report!
