### ISSUE TITLE
Ability to retain a larger history of directories

### ISSUE THREAD

**Issue by rien333** [jethrokuan/z#83]
I've noticed that some directories that I haven't visited in a while are sometimes forgotten by `z`. This could be intended behavior, of course. Still, working on different projects, it's a bit of bummer that I can't navigate quickly to a directory I once frequented. 

Is there a  way to configure how fast `z` forgets directories? Is there some sort of variable I can tweak to increase its "history" size?  Or would that go against the philosophy of the program?

**Comment by jethrokuan** [comment]
I don't think `z` ever forgets directories. There's however some confusing behaviour when `z` is run with sudo, resulting in the cache being otherwise write-protected. Are you doing anything sudo-related?

**Comment by rien333** [comment]
Nope, I never run `z` in conjunction with sudo. 

Running fish from git master, btw. I just noticed I haven't upgraded `fisher` or `z` in a while, will see if this weird behavior persists after upgrading.

Oddly enough, `~/.local/share/z/data` contained just 150 lines before I upgraded, which seems a bit low after more than a year of usage. Just now, I `cd`'ed to some directories that where not in the list, and they were added. So maybe this is fixed?

**Comment by jethrokuan** [comment]
I suspect it's because of the move of the cache file, to comply to XDG standards some time ago: https://github.com/jethrokuan/z/commit/c69b75ca43eb5e0c44f02e683029b1932fe0be33

**Comment by rien333** [comment]
I have had this machine since 2018/2019, so that seems fairly unlikely.

**Comment by rien333** [comment]
Don't think this still happens, but will keep an eye out.
