### ISSUE TITLE
in centos7.4 bash: argparse: command not found...

### ISSUE THREAD

**Issue by YanJa** [jethrokuan/z#91]
root@devserver ~/d/i/itour# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 

root@devserver ~/d/i/itour# z itour
bash: argparse: command not found...
~/.config/fish/functions/__z.fish (line 30):     argparse $options -- $argv
                                                 ^
in function '__z'
	called on line 25 of file ~/.config/fish/conf.d/z.fish
	with parameter list “itour”

in function 'z'
	called on standard input
	with parameter list “itour”

root@devserver ~/d/i/itour#

**Comment by krobelus** [comment]
> bash: argparse: command not found...

This is weird, why is it running bash when you're calling `z` from fish.
What's the output of `type argparse`? Maybe you have a script that overrides it, in that case using `builtin argparse` would work.

**Comment by YanJa** [comment]
I don't know, and i commented that line, no error now

**Comment by krobelus** [comment]
Oh well, yeah commenting it will disable any option parsing, then it always acts as if no flags were passed, which is alright for most uses I guess.

However, we should figure out why `argparse` does not work. Fish also uses it for git completions and some other functions, so you will probably run into problems at some point.

If you run `type argparse` and post the output we can try to help you. It should look like this:

```fish
$ type argparse
argparse is a builtin
```
